### ISSUE TITLE
Build issues, Error Configuring

### ISSUE THREAD

**Issue by fxsrt10** [polygraphene/ALVRClient#21]
I'm trying to build the app from source so I can add the ability to change IP addresses, but I'm getting a Error Configuring for the Project Sync and when I try to make I get a error "Cause: executing external native build for cmake\ALVRClient-2.3.1\ALVRClient-2.3.1\app\CMakeLists.txt"

**Comment by fxsrt10** [comment]
Here is the output of my "gradlew build --stacktrace"

```


> Configure project :app 
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html

> Task :app:generateJsonModelGithubARCoreDebug FAILED
External native generate JSON GithubARCoreDebug: starting JSON generation
External native generate JSON GithubARCoreDebug: using platform version 24 for ABI ARMEABI_V7A and min SDK version 24
External native generate JSON GithubARCoreDebug: rebuilding JSON C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\armeabi-v7a\android_gradle_build.json due to:
External native generate JSON GithubARCoreDebug: - expected json C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\armeabi-v7a\android_gradle_build.json file is not present, will remove stale json folder
External native generate JSON GithubARCoreDebug: - missing previous command file C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\armeabi-v7a\cmake_build_command.txt, will remove stale json folder
External native generate JSON GithubARCoreDebug: removing stale contents from 'C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\armeabi-v7a'
External native generate JSON GithubARCoreDebug: created folder 'C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\armeabi-v7a'
External native generate JSON GithubARCoreDebug: executing cmake Executable : C:\Users\vrtua\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe
arguments :
-HC:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app
-BC:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\armeabi-v7a
-DANDROID_ABI=armeabi-v7a
-DANDROID_PLATFORM=android-24
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\build\intermediates\cmake\GithubARCore\debug\obj\armeabi-v7a
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=C:\Users\vrtua\AppData\Local\Android\Sdk\ndk-bundle\android-ndk-r17c
-DCMAKE_CXX_FLAGS=
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a
-DCMAKE_SYSTEM_VERSION=24
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DCMAKE_ANDROID_NDK=C:\Users\vrtua\AppData\Local\Android\Sdk\ndk-bundle\android-ndk-r17c
-DCMAKE_TOOLCHAIN_FILE=C:\Users\vrtua\AppData\Local\Android\Sdk\ndk-bundle\android-ndk-r17c\build\cmake\android.toolchain.cmake
-G Ninja
jvmArgs :




[== "CMake Server" ==[

{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":1}],"type":"hello"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "handshake",
  "cookie": "gradle-cmake-cookie",
  "protocolVersion": {
    "isExperimental": true,
    "major": 1,
    "minor": 1
  },
  "sourceDirectory": "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app",
  "buildDirectory": "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/armeabi-v7a",
  "generator": "Ninja"
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"gradle-cmake-cookie","inReplyTo":"handshake","type":"reply"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "configure",
  "cacheArguments": [
    "",
    "-DANDROID_ABI\u003darmeabi-v7a",
    "-DANDROID_PLATFORM\u003dandroid-24",
    "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY\u003dC:\\Users\\vrtua\\Downloads\\ALVRClient-2.3.1\\ALVRClient-2.3.1\\app\\build\\intermediates\\cmake\\GithubARCore\\debug\\obj\\armeabi-v7a",
    "-DCMAKE_BUILD_TYPE\u003dDebug",
    "-DANDROID_NDK\u003dC:\\Users\\vrtua\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\android-ndk-r17c",
    "-DCMAKE_CXX_FLAGS\u003d",
    "-DCMAKE_SYSTEM_NAME\u003dAndroid",
    "-DCMAKE_ANDROID_ARCH_ABI\u003darmeabi-v7a",
    "-DCMAKE_SYSTEM_VERSION\u003d24",
    "-DCMAKE_EXPORT_COMPILE_COMMANDS\u003dON",
    "-DCMAKE_ANDROID_NDK\u003dC:\\Users\\vrtua\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\android-ndk-r17c",
    "-DCMAKE_TOOLCHAIN_FILE\u003dC:\\Users\\vrtua\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\android-ndk-r17c\\build\\cmake\\android.toolchain.cmake",
    "-G Ninja"
  ]
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"CMake Error: CMake was unable to find a build program corresponding to \"Ninja\".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.","title":"Error","type":"message"}

]== "CMake Server" ==]

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.


[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","progressCurrent":1000,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"Configuring incomplete, errors occurred!\nSee also \"C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/armeabi-v7a/CMakeFiles/CMakeOutput.log\".","type":"m
essage"}

]== "CMake Server" ==]

Configuring incomplete, errors occurred!
See also "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
Configuring incomplete, errors occurred!
See also "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/armeabi-v7a/CMakeFiles/CMakeOutput.log".


[== "CMake Server" ==[

{"cookie":"","errorMessage":"Configuration failed.","inReplyTo":"configure","type":"error"}

]== "CMake Server" ==]

Configuration failed.
External native generate JSON GithubARCoreDebug: using platform version 24 for ABI ARM64_V8A and min SDK version 24
External native generate JSON GithubARCoreDebug: rebuilding JSON C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\arm64-v8a\android_gradle_build.json due to:
External native generate JSON GithubARCoreDebug: - expected json C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\arm64-v8a\android_gradle_build.json file is not present, will remove stale json folder
External native generate JSON GithubARCoreDebug: - missing previous command file C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\arm64-v8a\cmake_build_command.txt, will remove stale json folder
External native generate JSON GithubARCoreDebug: removing stale contents from 'C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\arm64-v8a'
External native generate JSON GithubARCoreDebug: created folder 'C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\arm64-v8a'
External native generate JSON GithubARCoreDebug: executing cmake Executable : C:\Users\vrtua\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe
arguments :
-HC:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app
-BC:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\.externalNativeBuild\cmake\GithubARCoreDebug\arm64-v8a
-DANDROID_ABI=arm64-v8a
-DANDROID_PLATFORM=android-24
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1\app\build\intermediates\cmake\GithubARCore\debug\obj\arm64-v8a
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=C:\Users\vrtua\AppData\Local\Android\Sdk\ndk-bundle\android-ndk-r17c
-DCMAKE_CXX_FLAGS=
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a
-DCMAKE_SYSTEM_VERSION=24
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DCMAKE_ANDROID_NDK=C:\Users\vrtua\AppData\Local\Android\Sdk\ndk-bundle\android-ndk-r17c
-DCMAKE_TOOLCHAIN_FILE=C:\Users\vrtua\AppData\Local\Android\Sdk\ndk-bundle\android-ndk-r17c\build\cmake\android.toolchain.cmake
-G Ninja
jvmArgs :




[== "CMake Server" ==[

{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":1}],"type":"hello"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "handshake",
  "cookie": "gradle-cmake-cookie",
  "protocolVersion": {
    "isExperimental": true,
    "major": 1,
    "minor": 1
  },
  "sourceDirectory": "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app",
  "buildDirectory": "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/arm64-v8a",
  "generator": "Ninja"
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"gradle-cmake-cookie","inReplyTo":"handshake","type":"reply"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "configure",
  "cacheArguments": [
    "",
    "-DANDROID_ABI\u003darm64-v8a",
    "-DANDROID_PLATFORM\u003dandroid-24",
    "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY\u003dC:\\Users\\vrtua\\Downloads\\ALVRClient-2.3.1\\ALVRClient-2.3.1\\app\\build\\intermediates\\cmake\\GithubARCore\\debug\\obj\\arm64-v8a",
    "-DCMAKE_BUILD_TYPE\u003dDebug",
    "-DANDROID_NDK\u003dC:\\Users\\vrtua\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\android-ndk-r17c",
    "-DCMAKE_CXX_FLAGS\u003d",
    "-DCMAKE_SYSTEM_NAME\u003dAndroid",
    "-DCMAKE_ANDROID_ARCH_ABI\u003darm64-v8a",
    "-DCMAKE_SYSTEM_VERSION\u003d24",
    "-DCMAKE_EXPORT_COMPILE_COMMANDS\u003dON",
    "-DCMAKE_ANDROID_NDK\u003dC:\\Users\\vrtua\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\android-ndk-r17c",
    "-DCMAKE_TOOLCHAIN_FILE\u003dC:\\Users\\vrtua\\AppData\\Local\\Android\\Sdk\\ndk-bundle\\android-ndk-r17c\\build\\cmake\\android.toolchain.cmake",
    "-G Ninja"
  ]
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"CMake Error: CMake was unable to find a build program corresponding to \"Ninja\".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.","title":"Error","type":"message"}

]== "CMake Server" ==]

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.


[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","progressCurrent":1000,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"Configuring incomplete, errors occurred!\nSee also \"C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/arm64-v8a/CMakeFiles/CMakeOutput.log\".","type":"mes
sage"}

]== "CMake Server" ==]

Configuring incomplete, errors occurred!
See also "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/arm64-v8a/CMakeFiles/CMakeOutput.log".
Configuring incomplete, errors occurred!
See also "C:/Users/vrtua/Downloads/ALVRClient-2.3.1/ALVRClient-2.3.1/app/.externalNativeBuild/cmake/GithubARCoreDebug/arm64-v8a/CMakeFiles/CMakeOutput.log".


[== "CMake Server" ==[

{"cookie":"","errorMessage":"Configuration failed.","inReplyTo":"configure","type":"error"}

]== "CMake Server" ==]

Configuration failed.
External native generate JSON GithubARCoreDebug: JSON generation completed with problems


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelGithubARCoreDebug'.
> com.android.ide.common.process.ProcessException: Error configuring

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateJsonModelGithubARCoreDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.UncheckedException: com.android.ide.common.process.ProcessException: Error configuring
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
Caused by: com.android.ide.common.process.ProcessException: Error configuring
        at com.android.build.gradle.tasks.CmakeServerExternalNativeJsonGenerator.executeProcessAndGetOutput(CmakeServerExternalNativeJsonGenerator.java:198)
        at com.android.build.gradle.tasks.CmakeExternalNativeJsonGenerator.executeProcess(CmakeExternalNativeJsonGenerator.java:126)
        at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.buildAndPropagateException(ExternalNativeJsonGenerator.java:323)
        at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.build(ExternalNativeJsonGenerator.java:188)
        at com.android.build.gradle.tasks.ExternalNativeBuildJsonTask.build(ExternalNativeBuildJsonTask.java:35)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 41 more


* Get more help at https://help.gradle.org

BUILD FAILED in 1s
16 actionable tasks: 1 executed, 15 up-to-date

C:\Users\vrtua\Downloads\ALVRClient-2.3.1\ALVRClient-2.3.1>

```

**Comment by DenisShvetz** [comment]
Here is how I fixed this problem.

1. Locate C:\users\{your user name}\AppData\Local\Android\Sdk\cmake\{ CMake Version }\bin and make sure there is a ninja.exe in that directory.
2. Add this path to the PATH of environment variables list.
3. Restart Android Studio.

It should work. :)
